frontend_homepage:
    path:     /
    defaults: { _controller: "SiteMainBundle:Frontend/Main:index" }

frontend_partners:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/partners.yml"
    prefix: /partners

frontend_news:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/news.yml"
    prefix: /novosti

frontend_announcement:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/announcement.yml"
    prefix: /anons

frontend_event:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/event.yml"
    prefix: /turniry

frontend_media:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/media.yml"
    prefix: /miedia

frontend_players:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/player.yml"
    prefix: /players

frontend_baner:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/baner.yml"
    prefix: /baner

frontend_instagram:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/instagram.yml"
    prefix: /instagram

SitePollBundle_frontend:
    resource: "@SitePollBundle/Resources/config/routing/frontend.yml"
    prefix: /poll

frontend_search_index:
    path:     /search
    defaults: { _controller: "SiteMainBundle:Frontend/Search:index" }

frontend_pages:
    resource: "@SiteMainBundle/Resources/config/routing/frontend/page.yml"

