<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BanerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanerRepository extends EntityRepository
{
    function findRandom(){
        $count = $this->getEntityManager()->createQuery('
            SELECT count(b.id) FROM SiteMainBundle:Baner b
            WHERE b.onMain = 1
        ')
        ->getSingleScalarResult();

        $baner = $this->getEntityManager()->createQuery('
            SELECT b FROM SiteMainBundle:Baner b
            WHERE b.onMain = 1
        ')
        ->setFirstResult(rand(0, $count - 1))
        ->setMaxResults(1)
        ->getSingleResult();

        return $baner;
    }
}
