<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTeamRepository extends EntityRepository
{
    public function findAll(){
        return $this->findBy(array(), array('position' => 'ASC'));
    }
}
