<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Site\MainBundle\Entity\Event;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{

//  Поиск команд по типу матча
    public function findByEventType($type){
        switch($type){
            case 'chiempionat': {
                $typeNumber = Event::NAME_CHAMPIONSHIP;
            }break;
            case 'kubok': {
                $typeNumber = Event::NAME_CUP;
            }break;
            case 'ligha-ievropy': {
                $typeNumber = Event::NAME_EUROPA_LEAGUE;
            }break;
            case 'molodiozhnoie-piervienstvo': {
                $typeNumber = Event::NAME_YOUTH_CHAMPIONSHIP;
            }break;
            default: {
                $typeNumber = Event::NAME_CHAMPIONSHIP;
            }break;
        }

        $em = $this->getEntityManager();

        $teams = $em->createQuery('
            SELECT t FROM Site\MainBundle\Entity\Team t
            LEFT JOIN t.eventTeam et
            LEFT JOIN et.event e
            WHERE e.name = :typeNumber and e.datetime <= :now
        ')
            ->setParameters(array(
                'typeNumber' => $typeNumber,
                'now' => new \DateTime()
            ))
            ->getResult();

//        $teams = array();
//
//        foreach($events as $e){
//            foreach($e->getTeams() as $t){
//                $f = 0;
//                foreach($teams as $team){
//                    if($t->getId() == $team->getId()){
//                        $f = 1;
//                    }
//                }
//                if($f == 0){
//                    $teams[] = $t;
//                }
//            }
//        }

        return $teams;
    }
}
