<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Site\MainBundle\Entity\Event;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{

    public function findAll(){
        return $this->findBy(array(), array('name' => 'ASC'));
    }

//  Поиск команд по типу матча
    public function findByEventType($type){
        $query = '
            SELECT t FROM Site\MainBundle\Entity\Team t
            LEFT JOIN t.eventTeam et
            LEFT JOIN et.event e
            WHERE e.name = :typeNumber and e.datetime <= :now
            ORDER BY t.position ASC
        ';

        switch($type){
            case 'chiempionat': {
                $typeNumber = Event::NAME_CHAMPIONSHIP;
                $query = '
                    SELECT t FROM Site\MainBundle\Entity\Team t
                    LEFT JOIN t.eventTeam et
                    LEFT JOIN et.event e
                    WHERE e.name = :typeNumber and e.datetime > :now
                    ORDER BY t.position ASC
                ';
            }break;
            case 'kubok': {
                $typeNumber = Event::NAME_CUP;
            }break;
            case 'ligha-ievropy': {
                $typeNumber = Event::NAME_EUROPA_LEAGUE;
            }break;
            case 'dubliruiushchii-sostav-1': {
                $typeNumber = Event::NAME_YOUTH_CHAMPIONSHIP;
                $query = '
                    SELECT t FROM Site\MainBundle\Entity\Team t
                    LEFT JOIN t.eventTeam et
                    LEFT JOIN et.event e
                    WHERE e.name = :typeNumber and e.datetime > :now
                    ORDER BY t.positionM ASC
                ';
            }break;
            default: {
                $typeNumber = Event::NAME_CHAMPIONSHIP;
            }break;
        }

        $em = $this->getEntityManager();

        $teams = $em->createQuery($query)
            ->setParameters(array(
                'typeNumber' => $typeNumber,
                'now' => new \DateTime()
            ))
            ->getResult();

        return $teams;
    }

}
