<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MediaVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoMainRepository extends EntityRepository
{
    public function findFirstVideo(){
        $em = $this->getEntityManager();
        $count = $em->createQuery('
            SELECT COUNT(v.id) FROM Site\MainBundle\Entity\VideoMain v
            WHERE v.main = 0
        ')
            ->getSingleScalarResult();

        if($count > 0){
            return $em->createQuery('
                SELECT v FROM Site\MainBundle\Entity\VideoMain v
                WHERE v.main = 0
            ')
                ->setFirstResult(0)
                ->getSingleResult();
        }

        return false;
    }
}
